version: "3"

services:
  postgres-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=calendar
      - POSTGRES_PASSWORD=calendarpass
      - POSTGRES_USER=calendaruser
    volumes:
      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/1-ddl.sql
  calendar-api:
    build:
      context: .
    environment:
      - DATABASE_PLATFORM=postgres
      - DATABASE_URL=postgresql://postgres-db:5432/calendar
      - DATABASE_USERNAME=calendaruser
      - DATABASE_PASSWORD=calendarpass
    ports:
      - "18080:8080"
    depends_on:
      - postgres-db
    links:
      - "postgres-db:postgres-db"
    volumes:
      - ./scripts/wait-for-it.sh:/opt/app/wait-for-it.sh

    command: ["java", "-jar", "calendar-api-1.0.0.jar"]
